//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RenatoSfera.DOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mensagem
    {
        public int Id { get; set; }
        public string remetente { get; set; }
        public string texto { get; set; }
        public Nullable<int> showId { get; set; }
    
        public virtual Show Show { get; set; }
    }
}
